minionArt-Amish (2)
hackclub/blot pull request #951
Opened 2024-10-09 04:07 UTC by amishgupta7

Write a short description about your art piece, such as what your artwork represents and your experience drawing it!

My artwork shows a Minion from Despicable Me and drawing it was very fun and a little challenging. It was definitely a good experience learning how to use Blot and code using java. I haven't done much of it before so it was really fun.

- [x] I have read the steps to [getting a blot](https://github.com/hackclub/blot/blob/main/docs/GET_A_BLOT.md)
- [x] I have read all the [submission requirements](https://blot.hackclub.com/submitting) and follow them 
- [x] I am submitting art that...
  - [x] is algorithmically generated (will meaningfully change each time the program is run)
  - [x] is your own work that is not copied from somewhere else
  - [x] is drawable through the editor(does not use outside tools)
  - [x] doesn't call `Math.random()` (See the documentation on [randomness](https://github.com/hackclub/blot/blob/main/public/TOOLKIT.md#randomness))
  - [x] is drawable on Blot itself (doesn't have lines overlap more than 5 times)
    - [x] Doesn't overlap lines more than 5 times
    - [x] Fits in the working area of 125x125mm
    - [x] Doesn't rely on colour to look good

If you used based your art on something else, used a tutorial, or remixed it from something else, please link it here:
![image](https://github.com/user-attachments/assets/0e2ccf14-074e-4c72-8e3d-1e79ba92c7ca)

Lastly, link a picture of your art piece here:
<img width="707" alt="Minion1" src="https://github.com/user-attachments/assets/36b44341-6b24-451c-8660-62aed50bb1c5">

The actual code is without color.

2024-11-06 16:21 UTC, qcoral requested changes
hey - this is great, but does not meaningfully change between each version. keep working at it!

2024-12-09 04:54 UTC, amishgupta7 commented
Hi @qcoral, I created a new project so I could change it in more ways, can you please review it? I just uploaded it above the Minion one. Thanks!

2024-12-27 01:58 UTC, WolfGamer2 commented
Looks super cool!

2024-12-27 03:25 UTC, saumilthecode commented
Heyo!
nice art but the blot cant draw in colour
could you add a toggle to dissable/enable colours?

2024-12-27 04:37 UTC, saumilthecode commented
not too sure if its my blot or your art but the mountains dont get drawn 
![IMG_1704](https://github.com/user-attachments/assets/13cf1b12-1d55-4a15-a69c-5236e6ede95b)

it just stopped and started stabbing my table for about a minute straight before i stopped it🤷

2025-01-03 23:41 UTC, qcoral commented
this is great, but it relies heavily on colour - could you improve this to look good w/ lines only?

2025-01-27 19:48 UTC, closed without merging