Submission for somebody else
hackclub/blot pull request #960
Opened 2024-10-14 21:22 UTC by thelegendofmario

Write a short description about your art piece, such as what your artwork represents and your experience drawing it!

Next, make sure you go through **each item** in the following checklist. Delete this line after!

- [x] I have read the steps to [getting a blot](https://github.com/hackclub/blot/blob/main/docs/GET_A_BLOT.md)
- [x] I have read all the [submission requirements](https://blot.hackclub.com/submitting) and follow them 
- [x] I am submitting art that...
  - [x] is algorithmically generated (will meaningfully change each time the program is run)
  - [x] is your own work that is not copied from somewhere else
  - [x] is drawable through the editor(does not use outside tools)
  - [x] doesn't call `Math.random()` (See the documentation on [randomness](https://github.com/hackclub/blot/blob/main/public/TOOLKIT.md#randomness))
  - [x] is drawable on Blot itself (doesn't have lines overlap more than 5 times)
    - [x] Doesn't overlap lines more than 5 times
    - [x] Fits in the working area of 125x125mm
    - [x] Doesn't rely on colour to look good

If you used based your art on something else, used a tutorial, or remixed it from something else, please link it here:

Lastly, link a picture of your art piece here:
[link](https://cloud-ggc1pheyo-hack-club-bot.vercel.app/0island1.png)

2024-10-14 22:46 UTC, M0HID commented
Hey! This is a really cool project so far, but right now the buildings on the island sometimes overlap. Could you fix it and then ping me so I can re-review it?

2024-10-14 22:57 UTC, thelegendofmario commented
sure!

2024-10-16 20:52 UTC, thelegendofmario commented
@M0HID, I fixed it!

2024-10-19 14:33 UTC, thelegendofmario commented
@M0HID ?

2024-10-26 16:37 UTC, qcoral requested changes
hey! great start, but this needs more work - try adding some more details !!

2024-10-26 20:18 UTC, thelegendofmario commented
ok, thanks for replying!


On Sat, Oct 26, 2024 at 12:38 PM Alex Ren ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> hey! great start, but this needs more work - try adding some more details
> !!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/hackclub/blot/pull/960#pullrequestreview-2397294358>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A7EN5VHDGLWKWO2JZY5FAHDZ5PAPFAVCNFSM6AAAAABP5Y72JSVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDGOJXGI4TIMZVHA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2025-01-27 19:48 UTC, closed without merging