Leaf Effect
hackclub/blot pull request #986
Opened 2024-11-04 00:24 UTC by grandell1234

My piece of art is a sprig of leafs. They are three leafs that are randomly selected to go in different positions, which can lead to some cool art like what I linked below. It was very frustrating creating it, and this was close to the 6th rendition. I have spent way too much time on this at this point.

- [X] I have read the steps to [getting a blot](https://github.com/hackclub/blot/blob/main/docs/GET_A_BLOT.md)
- [X] I have read all the [submission requirements](https://blot.hackclub.com/submitting) and follow them 
- [X] I am submitting art that...
  - [X] is algorithmically generated (will meaningfully change each time the program is run)
  - [X] is your own work that is not copied from somewhere else
  - [X] is drawable through the editor(does not use outside tools)
  - [X] doesn't call `Math.random()` (See the documentation on [randomness](https://github.com/hackclub/blot/blob/main/public/TOOLKIT.md#randomness))
  - [X] is drawable on Blot itself (doesn't have lines overlap more than 5 times)
    - [X] Doesn't overlap lines more than 5 times
    - [X] Fits in the working area of 125x125mm
    - [X] Doesn't rely on colour to look good

Lastly, link a picture of your art piece here:
![snapshot3](https://github.com/user-attachments/assets/bd74bae2-fbd8-4dde-90d2-79ccd306b1f8)

2024-11-04 19:26 UTC, qcoral requested changes
This is great, but it's hard to tell the details of the different leaves. Could you make some changes?

2024-11-04 21:50 UTC, grandell1234 commented
I worked on it and got something like this:

![Screenshot 2024-11-04 at 3 48 00 PM](https://github.com/user-attachments/assets/636bedde-6181-4bc9-bd69-8ad79a2a7195)

Is this what you mean by it, the leafs are now obviously leafs. And if so, should I add that as an add on to this pull-request or create a new one.

2024-11-18 01:15 UTC, EnterpriseGoose commented
Hello! Sorry it's been so long. Just push your changes to your fork and it'll automatically update (including the preview link) over here. I look forward to seeing your changes!

2024-11-18 17:03 UTC, grandell1234 commented
Thanks @EnterpriseGoose, I have pushed the updated script, and snapshots.

2024-11-19 07:49 UTC, EnterpriseGoose commented
Great, thank you!
Looking at the project, I think the leaves are still a little tricky to differentiate. I also would love to see you add one final element to bring the project together into something that feels like a finished piece of art. Maybe you could make it so the leaves all generate along a branch? Or maybe you could add some more details to the shapes of the leaves that could randomize for each leaf? I just would love to see that one final teeny piece of it that brings it all together. I think you're super close! You got this!

2024-11-20 16:09 UTC, grandell1234 commented
I have worked on it for a bit, what do you think of this? It now has a center layer along with a ring outside of it. And there is a lot of variables people can adjust to get a lot of cool different designs.

![Screenshot 2024-11-20 at 10 03 23 AM](https://github.com/user-attachments/assets/45bab9f2-d527-45d1-a81d-d7afca4d92f5)
![Screenshot 2024-11-20 at 10 03 13 AM](https://github.com/user-attachments/assets/f80cabe5-9b80-4bb4-8c05-52fedcc1b1b7)
![Screenshot 2024-11-20 at 10 03 08 AM](https://github.com/user-attachments/assets/0dc4f805-0ad6-4395-9d4a-4f2bab6117fe)

2024-11-20 17:07 UTC, EnterpriseGoose commented
It looks great! Would you be able to push it so I can see the code?

2024-11-20 17:12 UTC, grandell1234 commented
Done, I just pushed the changes, with snapshots of course.

2024-11-20 18:08 UTC, EnterpriseGoose commented
I love it! It looks like a wreath! I'll send this off to Alex to see what he thinks.
If you wanted to go even further, you could also add some little flowers or little fruits interspersed throughout. I think it would look really pretty. I'll see what Alex thinks, though, in terms of if this is enough.

2025-01-06 18:29 UTC, qcoral commented
this is great, but it's hard to tell the differences between the layers of leaves - maybe have a different style for each ring??

2025-01-27 19:47 UTC, closed without merging